name: macOS Example Workflow

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  time-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Current Timer
        run: echo "The Current Time is ${date}"
