name: macOS Example Workflow
on:
  push:
    branches: 
      - main
  schedule:
    - cron: "*/2 * * * *"
jobs:
  time-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Current Timer
        run: echo "The Current Time is $(date)"
      